language: bash

sudo: required

services:
- docker

env:
  global:
    - secure: "EdzAUCue8az19YShQLrcyWQzwyg/kbhg4BIxRp6W68AiRNBhvH2P9gCEc7ZOnJZ9fM7jg8P8ZPGVvEskdz2rGDejKuFH27bKbmHyvhCaDa8C93PHTLt+pXnANOL9Opa10Qhbd46F+mFTvDUvFEAPCEZE5t3NFHqCSSUyX6zFILb5Yj02k/O1eXoO0hNQqihpEMum/SStHffqWdJeUD+H+FuhlTe8lc21DjrEUJGmyl1zQEUCk10CWbUo1qZsqbIlDkz+lT2+LBBXuUXAhNKp02Xw6xcwaKI96C0a5PJjWmtv7c+WPpQy1x5rDUeXivXeGZKN4lJe6tYWjg/Z2aBoAgc+O89QV5YLcLVIIewFuUlekOjwECk4tLpGrzthTtZAZbyrDEbK1WIDo7X7PgpW6Btkj1XzI/Fa/7RZoSzrO9cQJYhhtW9NEkA9idRPKzO8+/psTNTHr8shOLu3zJas6UAyESEcRXDP499ss1KnlVAniMP52oHJA+wx7YfDim8dRFXsUBNao2oh4zMi7+Duv5b/+9dWQ81G1okWiI+pKTP1UZo9T75Jx+CyUNaisOY7Ig3NNvoXQb90fdrbtKH7+hzZ1Q2dBG4W4H1M+cIw+iEQlv/gmMDfn1nAncWsSP5UZihJaQC3w3J7PAutMQsemhbz1jPqkJcxkze3iuiLfuw="
    - secure: "cqvKZcEQhQpikuSo2S3d9UKLz4nxO8Y+IgrjiWSy+ddfxJ1tSZ2T1AcT6OHQDIc1pEZoDMe2Xd8jBgkq34aY4dq/ziG1SGea00X/b/PO+Ps5p1ycGZ1JLbpphxhAOaAuhMwmTXhLcZwssSP5Wz/xsVuBl41R1/pW3Lxm9RyJEQi6TraUdw54eK4X6nbwyq4hFuU70sIy5CkCqdTu2HJ/6b3/lSX7O438ArvPMvHKNT+BvlfCI45qIW2bMb4KHjfYdjuli5t9kyoEnCuGQb7UFwkI5BgDtpAEhYd8mfn4cg3IXkJScSeGZoSXdZLFCP7Ym4/J6JETz/JGtRks2hdv1nkKlJwwIQ+5+m1MjnGvs/Q65phul0FrLqdHGQIEw8xtwXRJ8nJtv91rvlchQ7eI3Nw1MPCG+zFQfYphB9XEFA9BtxBm8+LP6SneTOMWdYX/bCmyjTP+ao21qVAE+XvRij8/k40h8HX5xCiwzcZntU43cWs09hzBTUANdyeoKqCjwFDV58bA9cQHKu4fLqCGPGkMRWlR3jC3T1pLTa/GSOUYUwxxQREeSnjVWwaNEtDXTPHOmVB4vQuaDPh0yirdBpLLtV+utbMsp6JkAGPF43X/qHf+pds8EnEugNtYzLBcQzZqRWmFDlWR5KV3uMtKomEuh4FNZEwtsSgd5eO8m9w="
    - secure: "ttII3KtIW84RQ6Zx0Tt1G8F1p2cr3x9qcppIGLaKO/HtXgPt6F1IpwZ6Uj5sVANwKfYzmHjZ5n5tqJUZUH2gNqdSSB8XI89ln/WRahJTRvG8l4u4HEI11VbAte6fHY1jRo3RU/nHJE1c5YdpFrV3fTmOlnB2FNvOIUmsElYkCzjzQPegfsniObJ1eEVNYwaimap/XFm1FiXci37MbIimwrvJJ1sZXhG1Dowo4Ik52QQytU4OGa51Sj5kEEnqj+dxndFL5F2X6k+NLL/1DBIXHykegimZUHtGL7dkfMwyBg1HkyPtNH3vwslCC4J2dCC9clJpfmpXVVCwuKcg/ujiH8mwo4Cgfl1p6BIU0+lueqilavszrf8cTKt06Hgr3Q0/qeqEvXhjiPqzPIEBltZbhNvOgKTXKvILuQD+VcVMvMCwqEUXmOJKZMUrdKVAnKXX0klqLTWgSa2PJE6WqL0sscMmQp+HEIDkAsc2YVI/1vpsvoAgLoBBRn2bncfTgbtsd0qbFVncG22c3tA+8Mt4WW8agTCG0gAwe568TVgh1Eb+WgfZKP8a3T5yHUVVdAu0GxRBErw9uLx4AFEkrKrhIcCFVYoKL20+m+xL9weyuZ3fftEFWvZ4eEXDQt0j2DASuBt05Lig+oWYo8X4lcE7MICyHwsc5BDBBJ2DtvKxpMs="
    - PROJECT="mumble"
    - REPOSITORY="encodeering"
    - BRANCH="$TRAVIS_BRANCH"
  matrix:
    - ARCH="amd64" VERSION="3.2.1" VARIANT="dj"
    - ARCH="armhf" VERSION="3.2.1" VARIANT="dj"
    - ARCH="amd64" VERSION="1.2.19" VARIANT="murmur"
    - ARCH="armhf" VERSION="1.2.19" VARIANT="murmur"

install:
- bash <(curl https://raw.githubusercontent.com/encodeering/docker-ci/master/install.sh) 0.1.7

before_script:
- sudo -E bash ./module.sh "." "./setup.sh"

script:
- sudo -E bash ./module.sh "modules/$VARIANT" "./build.sh"

after_script:
- docker images

deploy:
  script: sudo -E bash ./module.sh "." "./release.sh"
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
