diff --git a/library/murmur/Dockerfile b/library/murmur/Dockerfile
index bb0dac4..141b24c 100644
--- a/library/murmur/Dockerfile
+++ b/library/murmur/Dockerfile
@@ -1 +1 @@
-FROM alpine:latest
+FROM alpine:3.7
@@ -10,16 +10,7 @@ COPY ./docker-entrypoint.sh /usr/local/bin/
-RUN apk --no-cache add \
-        pwgen \
-        libressl \
-    && adduser -SDH murmur \
-    && mkdir \
-        /data \
-        /opt \
-        /var/run/murmur \
-    && chown -R murmur:nobody \
-        /var/run/murmur \
-        /etc/murmur \
-    && wget \
-        https://github.com/mumble-voip/mumble/releases/download/${MURMUR_VERSION}/murmur-static_x86-${MURMUR_VERSION}.tar.bz2 -O - |\
-        bzcat -f |\
-        tar -x -C /opt -f - \
-    && mv /opt/murmur* /opt/murmur
+RUN apk --no-cache add shadow icu-libs murmur=1.2.19-r4 pwgen libressl      \
+ && rm /etc/murmur.ini /etc/init.d/murmur /etc/dbus-1/system.d/murmurd.conf \
+ && usermod  -u 1000 murmur \
+ && groupmod -g 1000 murmur \
+ && mkdir -p               /data /var/run/murmur             \
+ && chown -R murmur:nobody /data /var/run/murmur /etc/murmur \
+ && apk del shadow
@@ -37,0 +29 @@ ENTRYPOINT ["docker-entrypoint.sh"]
+CMD "chown"
